---
- name: stop application in Tomcat8
  hosts: linuxtomcat
#  strategy: debug
  become: yes


  tasks: 
    - name: stop tomcat application
      uri:
        url: http://localhost:8080/manager/text/list
#        method: GET
        user: ansible
        password: secret
        return_content: yes
      register: result

    - name: Showing Result
      debug: 
        msg:  "{{ result.content }}"
