---
# tasks file for Docker_andotherstuff

- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: Copying template_repo on remote service
  template: src=docker.j2 dest={{ dst_folder }}/docker.list mode=0555

- name: Installing deps
  apt:  name={{ item }} state=present
  update_cache: yes
  cache_valid_time: 3600
  with_items:
  - apt-transport-https
  - ca-certificates

- name: Installing Docker
  apt: name={{ item }} state=present
  with_items:
  - docker-engine
